"""Generates Android string resources (en, te, hi) and the Kotlin lookup map from translations.json.

Workflow for new UI text:
  1. Write English text in the code as usual.
  2. python tools/i18n/extract.py --apply   (wraps new user-facing texts in tr(...), lists them in table.json)
  3. Add Telugu and Hindi for any new text to translations.json ("English": ["తెలుగు", "हिन्दी"])
  4. python tools/i18n/generate.py          (rewrites strings_i18n.xml files and I18nKeys.kt)
Texts missing from translations.json fall back to English at runtime and are reported here.
"""
import hashlib, json, os, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
MAIN = ROOT / 'frontend/app/src/main'
d = json.load(open(pathlib.Path(__file__).with_name('translations.json'), encoding='utf-8'))
keys = sorted(d)

def key_for(fmt):
    words = re.findall(r'[A-Za-z]+', fmt.lower())[:6]
    return 'i18n_' + ('_'.join(words) or 'text')[:48] + '_' + hashlib.md5(fmt.encode()).hexdigest()[:6]

names = {k: key_for(k) for k in keys}
assert len(set(names.values())) == len(names), 'resource name collision'

def check(k, v, lang):
    if sorted(re.findall(r'%\d\$s', k)) != sorted(re.findall(r'%\d\$s', v)):
        sys.exit(f'placeholder mismatch [{lang}] {k!r} -> {v!r}')

def xml_value(v):
    v = v.replace('\\', '\\\\').replace('"', '\\"').replace("'", "\\'")
    return '"' + v.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;') + '"'

def write(folder, idx, lang):
    out = ['<?xml version="1.0" encoding="utf-8"?>',
           '<!-- Generated by tools/i18n/generate.py from translations.json. Edit that file, then regenerate. -->',
           '<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingTranslation,UnusedResources">']
    for k in keys:
        v = k if idx is None else d[k][idx]
        check(k, v, lang)
        fmt = ' formatted="false"' if '%' not in v else ''
        out.append(f'    <string name="{names[k]}"{fmt}>{xml_value(v)}</string>')
    out.append('</resources>\n')
    (MAIN / f'res/{folder}').mkdir(parents=True, exist_ok=True)
    (MAIN / f'res/{folder}/strings_i18n.xml').write_text('\n'.join(out), encoding='utf-8')

write('values', None, 'en'); write('values-te', 0, 'te'); write('values-hi', 1, 'hi')

def kt(s): return s.replace('\\', '\\\\').replace('"', '\\"').replace('$', '\\$')
lines = ['package com.iamode.app.core.i18n', '', 'import com.iamode.app.R', '',
         '/** Generated by tools/i18n/generate.py: English source text → string resource. Do not edit by hand. */',
         f'internal val I18N_KEYS: Map<String, Int> = HashMap<String, Int>({len(keys) * 2}).apply {{']
lines += [f'    put("{kt(k)}", R.string.{names[k]})' for k in keys] + ['}', '']
(MAIN / 'java/com/iamode/app/core/i18n/I18nKeys.kt').write_text('\n'.join(lines), encoding='utf-8')

table = pathlib.Path(__file__).with_name('table.json')
if table.exists():
    missing = [k for k in json.load(open(table, encoding='utf-8')) if k not in d]
    if missing: print('Not translated yet (shown in English):', *missing, sep='\n  ')
print(f'{len(keys)} strings × 3 languages generated')
